### ISSUE TITLE
Add ability to include/exclude posts by author in feed

### ISSUE THREAD

**Issue by avcascade** [Automattic/newspack-rss-enhancements#9] opened 2021-07-21 01:53 UTC
In addition to adding the ability to include/exclude posts by tag (as requested in Automattic/newspack-plugin#1899), it would be helpful to have the ability to include or exclude posts by **_author_**. This would enable RSS feeds to be created that are based solely on groups of authors (like a Staff RSS feed, for example, or a Guest Contributors feed) without the need to rely on categories or tags (i.e. Guest Submissions). This would also open a lot of other possibilities for custom feeds in conjunction with the category and tag filtering.

**Comment by adekbadek** [comment] 2022-08-16 12:23
Duplicate of https://github.com/Automattic/newspack-plugin/issues/1903

**Closed as completed by adekbadek** 2022-08-16 12:23 UTC
